# Generated by Django 5.0.2 on 2024-02-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='charcode',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.DateField(),
        ),
    ]
